_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 2
                - 3
                - 11
                - 12
                - 41
                - 49
                - 51
                - 55
                - 71
                - 105
            "2":
                - 1
                - 2
                - 3
                - 11
                - 12
                - 41
                - 49
                - 51
                - 55
                - 71
                - 105
            "3":
                - 2
                - 19
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.7
            "6": 4.46.3
            "8":
                - 1
                - 2
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 20
learning_rate:
    value: 0.0001
