name: Model Training and Evaluation Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m venv venv  # Create virtual environment named venv
        source venv/bin/activate  # Activate the virtual environment
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Log in to WandB
      run: |
        source venv/bin/activate  # Activate the virtual environment
        echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV
        wandb login ${{ secrets.WANDB_API_KEY }}  # Login to WandB

  train_model:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run model training
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python scripts/model_training.py  # Run the model training script

  validate_model:
    needs: train_model
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run model validation
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python scripts/validate_model.py  # Run model validation script

  publish_model:
    needs: validate_model
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Publish model to Hugging Face
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python scripts/publish_to_hf.py  # Publish the model to Hugging Face
