name: Model Training and Evaluation Pipeline

on:
  push:
    branches: [main]

jobs:

  train_model:
    runs-on: ubuntu-latest

    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      HF_TOKEN: ${{ secrets.HF_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.7"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Login WandB
        run: wandb login $WANDB_API_KEY

      - name: Run training
        run: python model_training.py
