name: Model Training and Evaluation Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:

  validate_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4  
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run model validation
      run: |
        python validate_model.py
