name: Model Training and Evaluation Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to WandB
      run: |
        echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV
        wandb login ${{ secrets.WANDB_API_KEY }}

  train_model:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run model training
      run: |
        python model_training.py

  validate_model:
    needs: train_model
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run model validation
      run: |
        python validate_model.py

  publish_model:
    needs: validate_model
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish model to Hugging Face
      run: |
        python publish_to_hf.py
